app/controllers/core_induction_programme/lessons_controller.rb
app/controllers/core_induction_programme/modules_controller.rb
app/controllers/core_induction_programme/years_controller.rb
app/views/core_induction_programme/lessons/edit.html.erb
app/views/core_induction_programme/modules/edit.html.erb
app/views/core_induction_programme/years/edit.html.erb
spec/requests/core_induction_programme/course_lesson_spec.rb
spec/requests/core_induction_programme/course_module_spec.rb
spec/requests/core_induction_programme/course_year_spec.rb

Copy of https://github.com/DFE-Digital/early-careers-framework/pull/89

Edit course titles

---

.eslintrc.js
.github/workflows/test.yml
.gitignore
Gemfile
Gemfile.lock
README.md
config/initializers/cypress_on_rails.rb
package.json
spec/cypress.json
spec/cypress/app_commands/activerecord_fixtures.rb
spec/cypress/app_commands/clean.rb
spec/cypress/app_commands/eval.rb
spec/cypress/app_commands/factory_bot.rb
spec/cypress/app_commands/log_fail.rb
spec/cypress/app_commands/scenarios/basic.rb
spec/cypress/cypress_helper.rb
spec/cypress/fixtures/example.json
spec/cypress/integration/aaa-meta.js
spec/cypress/plugins/index.js
spec/cypress/support/commands.js
spec/cypress/support/index.js
spec/cypress/support/on-rails.js
yarn.lock

It's pretty much the same as the setup from the other repo, just with slightly different tests.

Add Cypress

---

Gemfile
Gemfile.lock
config/routes.rb
spec/cypress/fixtures/govspeak-all.txt
spec/cypress/integration/accessibility.js

Govspeak PR fixing accessibility issues: https://github.com/DFE-Digital/ecf-govspeak/pull/10
This PR will fail until that is merged.

Add test for govspeak accessibility

---

app/controllers/users/sessions_controller.rb
app/views/core_induction_programme/years/show.html.erb
db/seeds/dummy_structures.rb

We want to log in as dummy users on staging - we use it for content editing

Fix staging environment

---

app/controllers/users/sessions_controller.rb
app/models/course_lesson.rb
app/views/core_induction_programme/years/show.html.erb
app/webpacker/styles/app_task_list.scss
db/seeds/dummy_structures.rb
spec/models/course_lesson_spec.rb

I want to fix logging in on staging.

Release to staging, number 3

---

app/webpacker/packs/cookie-banner.js
spec/cypress/integration/cookies.js

Same code as other PR: https://github.com/DFE-Digital/early-careers-framework/pull/127

Fix cookie banner

---

.eslintrc.js
app/views/dashboard/show.html.erb
app/views/layouts/application.html.erb
app/webpacker/styles/application.scss
app/webpacker/styles/dashboard.scss
package.json
spec/cypress/integration/aaa-meta.js
spec/cypress/integration/accessibility.js
spec/factories/early_career_teacher_profiles.rb
yarn.lock

https://dfedigital.atlassian.net/browse/CPDEL-239
None yet as it's mostly placeholder stuff so functionality can't be tested yet

Add mostly-placeholder ECT dashboard

---

app/controllers/username_controller.rb
app/models/user.rb
app/views/dashboard/show.html.erb
app/views/username/edit.html.erb
app/webpacker/styles/dashboard.scss
config/routes.rb
db/migrate/20210407113051_add_username_to_users.rb
db/schema.rb
spec/cypress/integration/Cookies.feature
spec/cypress/integration/Username.feature
spec/cypress/support/commands.js
spec/cypress/support/step_definitions/common-interaction.js
spec/cypress/support/step_definitions/common-navigation.js
spec/cypress/support/step_definitions/factory-bot.js
spec/requests/username_request_spec.rb

https://dfedigital.atlassian.net/browse/CPDEL-212
Also pulls in some cucumber-related changes from the other repo
yes

Give users the ability to set a username

---

README.md
app/views/cookies/_banner.html.erb
app/views/cookies/show.html.erb
app/views/layouts/application.html.erb
app/views/start/index.html.erb

https://dfedigital.atlassian.net/browse/CPDEL-286
We want service name updated
Update service name in page title, headers, and in cookies
N/A
Check if it looks alright in the review app

CPDEL-286: Update service name in user-facing places

---

app/controllers/application_controller.rb
app/controllers/signed_out_controller.rb
app/views/signed_out/show.html.erb
config/locales/devise.en.yml
config/routes.rb
spec/cypress/integration/aaa-meta.js
spec/cypress/support/commands.js
spec/requests/signed_out_request_spec.rb
spec/requests/users/logout_spec.rb

https://dfedigital.atlassian.net/browse/CPDEL-298
Didn't add a cypress test - I feel like it would only be useful if we had visual tests, which we don't on this repo atm

Add new page for when signed out

---

spec/cypress.json
spec/cypress/integration/accessibility.js
spec/cypress/support/commands.js

Also, speed up the test by not loading the youtube iframes

Test accessibility of lesson parts, not lessons

---

app/views/layouts/_page_navigation.html.erb
app/views/layouts/application.html.erb
lib/devise/strategies/yolo_authenticatable.rb
spec/cypress/integration/Login.feature
spec/cypress/integration/Navigation.feature
spec/cypress/integration/accessibility.js
spec/cypress/support/commands.js
spec/cypress/support/step_definitions/common-interaction.js

https://dfedigital.atlassian.net/browse/CPDEL-301
We got some fairly specific requirements for what should be displayed in the navigation.
1. Make govuk point at gov.uk
2. Remove login navigation element
3. Make service name element take user to dashboard when user is logged in
4. Add cypress tests for it all 
I hope I included all the needed tests.
With cypress. In the review app, I recommend checking the logged out part first, then the part when user is in the create account flow, and finally the part when user is fully logged in.

CPDEL-301: Improve navigation and add tests for it

---

app/views/core_induction_programmes/modules/show.html.erb
spec/cypress/integration/CipStoriesAdmin.feature

https://dfedigital.atlassian.net/browse/CPDEL-285
Turns out there was only one in this repo!

Fix accessibility issue and add test

---

Gemfile
Gemfile.lock
config/environments/deployed_development.rb
config/environments/production.rb
config/environments/staging.rb
config/initializers/rack_atack.rb
spec/cypress/support/on-rails.js
spec/requests/core_induction_programme/course_lesson_part_spec.rb
spec/requests/core_induction_programme/course_lesson_spec.rb
spec/requests/core_induction_programme/course_module_spec.rb
spec/requests/core_induction_programme/course_year_spec.rb
spec/requests/core_induction_programme/progress_spec.rb

Like https://github.com/DFE-Digital/early-careers-framework/pull/280 - we had similar vulnerabilities, so we should probably include the quick fixes for them in our repo.

Pentest fixes

---

db/seeds.rb
spec/cypress/app_commands/load_seed.rb

Hope for the best. Just for code readability.

Remove in-memory dictionaries for loading seed files

---

lib/devise/strategies/yolo_authenticatable.rb
spec/cypress/integration/Login.feature

https://dfedigital.atlassian.net/browse/CPDEL-340
yes

Better errors when login fails

---

app/policies/core_induction_programme_policy.rb
app/views/dashboard/show.html.erb
spec/cypress/app_commands/scenarios/mentor_cip.rb
spec/cypress/integration/CipStoriesMentor.feature
spec/policies/core_induction_programme_policy_spec.rb

prep work for a future ticket
yes

Give mentors the ability to access mentee's CIP

---

app/views/dashboard/show.html.erb

i'm an idiot. merged prs in wrong order. this is the fix 😅

Use ect name, not preferred name

---

app/views/core_induction_programmes/lesson_parts/show.html.erb
spec/cypress/integration/CipStoriesAdmin.feature
spec/cypress/integration/CipStoriesECT.feature
spec/cypress/support/step_definitions/common-interaction.js

https://dfedigital.atlassian.net/browse/CPDEL-381
The ticket is for updating copy. I also cleaned up our cypress tests a little. 
Changed copy to match the ticket.
Clean up cucumber tests.

CPDEL-381: Update progress tracking copy

---

app/controllers/core_induction_programmes/lesson_parts_controller.rb
app/controllers/core_induction_programmes/lessons_controller.rb
app/policies/core_induction_programme_policy.rb
app/policies/course_lesson_part_policy.rb
app/policies/course_lesson_policy.rb
app/policies/course_module_policy.rb
app/policies/course_year_policy.rb
spec/cypress/integration/aaa-meta/cypress.js
spec/policies/course_lesson_part_policy_spec.rb
spec/policies/course_lesson_policy_spec.rb
spec/policies/course_module_policy_spec.rb
spec/policies/course_year_policy_spec.rb
spec/requests/core_induction_programme/course_lesson_part_spec.rb
spec/requests/core_induction_programme/course_lesson_spec.rb
spec/requests/core_induction_programme/course_module_spec.rb
spec/requests/core_induction_programme/course_year_spec.rb

from the backlog of michal 🧠 (aka no ticket)
yes 😩

Ensure that only correct users can access year/module/lesson pages

---

app/models/early_career_teacher_profile.rb
app/models/mentor_profile.rb
app/models/user.rb
app/policies/core_induction_programme_policy.rb
app/policies/course_lesson_part_policy.rb
app/policies/course_lesson_policy.rb
app/policies/course_module_policy.rb
app/policies/course_year_policy.rb
app/views/dashboard/show.html.erb
db/migrate/20210517105706_add_core_induction_programme_to_mentors.rb
db/schema.rb
db/seeds/dummy_structures.rb
spec/cypress/app_commands/scenarios/ect_cip.rb
spec/cypress/app_commands/scenarios/mentor_cip.rb
spec/cypress/integration/CipStoriesMentor.feature
spec/factories/mentor_profiles.rb
spec/models/early_career_teacher_profile.rb
spec/models/mentor_profile_spec.rb
spec/policies/core_induction_programme_policy_spec.rb
spec/policies/course_lesson_part_policy_spec.rb
spec/policies/course_lesson_policy_spec.rb
spec/policies/course_module_policy_spec.rb
spec/policies/course_year_policy_spec.rb
spec/requests/core_induction_programme/core_induction_programme_spec.rb
spec/requests/core_induction_programme/course_lesson_part_spec.rb
spec/requests/core_induction_programme/course_lesson_spec.rb
spec/requests/core_induction_programme/course_module_spec.rb
spec/requests/core_induction_programme/course_year_spec.rb
spec/requests/training_and_support_request_spec.rb

https://dfedigital.atlassian.net/browse/CPDEL-377
yes

Add CIPs to mentors, remove mentees

---

app/views/dashboard/show.html.erb
app/views/training_and_support/_guidance_ambition_institite.html.erb
app/views/training_and_support/_guidance_education_development_trust.html.erb
app/views/training_and_support/_guidance_teach_first.html.erb
app/views/training_and_support/_guidance_ucl.html.erb
spec/cypress/integration/TrainingAndSupport.feature

https://dfedigital.atlassian.net/browse/CPDEL-315
yes

Add copy for guidance pages

---

README.md
documentation/credentials.md
documentation/dealing_with_cip_content.md
documentation/debugging_in_govpaas.md
documentation/register_and_partner_api_setup.md
documentation/terraform.md
documentation/updating_images_in_cip_content.md

Our readme and docs were a bit out of date.
Write a few documentation files.
Read those files, check if they make sense to you - cause you will be using them later.

Update readme and add a few documents

---

app/views/core_induction_programmes/years/_module_list.html.erb
app/views/training_and_support/show.html.erb

https://dfedigital.atlassian.net/browse/CPDEL-460
- Remove "X self-study sessions" text for mentors
- Make guidelines 2/3 wide

Small visual fixes:

---

spec/cypress/integration/accessibility.js

from the backlog of michal 🧠 
yes

Add accessibility tests for mentor materials

---

app/views/core_induction_programmes/lesson_parts/show_split.html.erb
app/views/dashboard/_dashboard_ect.html.erb
app/views/dashboard/_dashboard_mentor.html.erb
app/views/dashboard/show.html.erb
app/views/layouts/application.html.erb
app/webpacker/styles/dashboard.scss
spec/cypress/integration/CipYears.feature
spec/cypress/integration/Dashboard.feature
spec/cypress/integration/Login.feature
spec/cypress/integration/PreferredName.feature
spec/cypress/integration/TrainingAndSupport.feature
spec/cypress/support/step_definitions/common-interaction.js

https://dfedigital.atlassian.net/browse/CPDEL-418
yes

Mentor dashboard

---

Gemfile
Gemfile.lock
app/jobs/sync_users_job.rb
bin/delayed_job
config/environments/deployed_development.rb
config/environments/production.rb
config/environments/staging.rb
lib/devise/strategies/yolo_authenticatable.rb
lib/tasks/cron.rake
spec/lib/devise/strategies/yolo_authenticatable_spec.rb
terraform/app/modules/paas/main.tf
terraform/app/modules/paas/variables.tf
terraform/app/terraform.tf
terraform/app/variables.tf
terraform/workspace-variables/dev.tfvars
terraform/workspace-variables/review.tfvars
terraform/workspace-variables/staging.tfvars

Ticket: https://dfedigital.atlassian.net/browse/CPDEL-518
Going commit-by-commit should make things more understandable. I decided to add a worker app to staging, to see how it will perform. Copied that one from R&P. 
2. So long as you clicked 5 minutes or later from the app being created, you should be able to log in with `rp-ect-ambition@example.com` - a user that we can only get from their API.

CPDEL-518: Sync users periodically

---

app/mailers/user_mailer.rb
app/services/utm_service.rb
app/views/layouts/application.html.erb
lib/devise/strategies/passwordless_authenticatable.rb

Ticket: [482](https://dfedigital.atlassian.net/browse/CPDEL-482) and [497](https://dfedigital.atlassian.net/browse/CPDEL-497)
It's essentially how R&P have done it. The tests weren't liking it when Utm was named uppercase so have named as it is. 
Check data is available in GA. Speak to Chris Baird

Add google analytics

---

app/models/api_metadata.rb
app/services/register_and_partner_api/sync_users.rb
app/services/register_and_partner_api/sync_users_timer.rb
db/migrate/20210604103110_add_api_metadata.rb
db/schema.rb
spec/services/register_and_partner_api/sync_users_spec.rb
spec/spec_helper.rb

Ticket: https://dfedigital.atlassian.net/browse/CPDEL-382
I switched to using regex in tests to determine which requests to stub, because we are using query params, and knowing exactly what they will be is way too hard.
1. You can't

CPDEL-382: Track and send last time we used the users api

---

.github/workflows/deploy_to_dev.yml
.github/workflows/deploy_to_production.yml
.github/workflows/deploy_to_staging.yml
.github/workflows/review.yml
Gemfile
Gemfile.lock
config/environments/deployed_development.rb
config/environments/production.rb
config/environments/staging.rb
terraform/app/modules/paas/main.tf
terraform/app/modules/paas/variables.tf
terraform/app/terraform.tf
terraform/app/variables.tf

Ticket: https://dfedigital.atlassian.net/browse/CPDEL-550
Copied pretty much everything from R&P.
I intend to see if I get any logs from E&L in the existing logstash setup, if yes it is probably working.

Add logstash

---

app/helpers/application_helper.rb
app/models/analytics_data_layer.rb
app/models/user.rb
app/views/layouts/application.html.erb
spec/helpers/application_helper_spec.rb
spec/models/analytics_data_layer_spec.rb

Ticket: https://dfedigital.atlassian.net/browse/CPDEL-483
I also decided to steal some code from R&P to include some extra data about the user - because I think we want it.
You can't, not without a look into GA. And even then, this needs to be deployed to prod before we can test that it shows up correctly.

Add google analytics to production

---

app/components/lesson_summary_component.html.erb
app/components/lesson_summary_component.rb
app/views/core_induction_programmes/modules/show.html.erb
app/views/core_induction_programmes/years/_module_list.html.erb
app/webpacker/styles/app_task_list.scss
spec/cypress/integration/CipLessons.feature
spec/cypress/integration/CipModules.feature
spec/requests/core_induction_programme/course_module_spec.rb

Ticket: https://dfedigital.atlassian.net/browse/CPDEL-526
Purely frontend change. Technically, the minimal change satisfying the requirements would be the first commit (I think). But I think we were adding stuff to this one view for a long time, and I decided to split some of it out - so I made a component for displaying lesson summary. Hopefully it should make things easier to read - I don't imagine we will gain much reusability from it.
I might look into adding automated tests for components (stealing a lot of setup for it from R&P), but it's probably beyond the scope of this PR. 

CPDEL-526: Link to mentor materials

---

config/initializers/canonical_rails.rb
terraform/app/modules/paas/data.tf
terraform/app/modules/paas/main.tf
terraform/app/modules/paas/variables.tf
terraform/app/terraform.tf
terraform/app/variables.tf
terraform/workspace-variables/production.tfvars
terraform/workspace-variables/production_app_env.yml
terraform/workspace-variables/staging.tfvars
terraform/workspace-variables/staging_app_env.yml

We want some custom domains!
Copy-pasted from R&P, I think it should just work. Will need to deploy to staging to make sure.

Custom domains

---

terraform/workspace-variables/production.tfvars
terraform/workspace-variables/staging.tfvars

Copy pasted with an error so staging deploy failed 😢

Custom domains round 2

---

terraform/app/modules/paas/main.tf

I forgot to bind the routes to the app, rookie mistake.

Actually map the routes to the app

---

app/controllers/application_controller.rb
app/controllers/healthcheck_controller.rb
config/routes.rb

No ticket, just wanted to copy-paste Ethan's hard work.

Copy R&P's fancier healthcheck

---

app/services/register_and_partner_api/sync_users.rb
terraform/workspace-variables/dev_app_env.yml
terraform/workspace-variables/production_app_env.yml
terraform/workspace-variables/review_app_env.yml
terraform/workspace-variables/staging_app_env.yml

Turns out adding pagination can be tricky. I will play around with the review app to make sure it behaves the way I expect it.
I think the real fix is removing front slashes from R&P urls. But just in case I added some more safety measures, like `sleep(1)` and checking whether we got any new R&P ids.

Fix pagination 2

---

app/controllers/application_controller.rb
app/controllers/core_induction_programmes/lesson_parts_controller.rb
app/controllers/core_induction_programmes/lessons_controller.rb
app/controllers/core_induction_programmes/mentor_materials_controller.rb
app/controllers/core_induction_programmes/modules_controller.rb
app/controllers/core_induction_programmes/years_controller.rb
app/controllers/core_induction_programmes_controller.rb
app/models/analytics_data_layer.rb

Ticket: https://dfedigital.atlassian.net/browse/CPDEL-498

CPDEL-498: Add more information to the data layer

---

Gemfile
Gemfile.lock
app/views/core_induction_programmes/years/_module_list.html.erb
config/application.rb

Ticket:
[539](https://dfedigital.atlassian.net/jira/software/projects/CPDEL/boards/89?assignee=5f3543bb3e9e2e004db3189d&selectedIssue=CPDEL-539)
2. Sign in as an ECT `ambition-early-career-teacher@example.com
3. Click 'Go to your module materials'

CPDEL-539 change number of self-study sessions to digits

---

app/models/invite_email_mentor.rb

Ticket:
[592](https://dfedigital.atlassian.net/browse/CPDEL-592)

Push mentor onboarding email date back to 31/08/2021

---

Gemfile
Gemfile.lock
app/webpacker/styles/govspeak.scss
app/webpacker/styles/govspeak/_section.scss

Ticket: https://dfedigital.atlassian.net/browse/CPDEL-598
2. Type `/govspeak_test` in the url
3. Copy-paste the text below into the field, see how it previews.
```
$Section
- some list
- some more list
Or some content in paragraphs
$Section
```

Update govspeak version to include a section component

---

app/controllers/core_induction_programmes/modules_controller.rb
app/models/course_module.rb
app/views/core_induction_programmes/modules/_course_module_fields.html.erb
app/views/core_induction_programmes/modules/show.html.erb
db/migrate/20210623192046_add_page_header_to_course_module.rb
db/schema.rb
spec/cypress/integration/CipModules.feature
spec/cypress/support/step_definitions/common-interaction.js
spec/models/course_module_spec.rb
spec/requests/core_induction_programme/course_module_spec.rb

Ticket:
[584](https://dfedigital.atlassian.net/jira/software/projects/CPDEL/boards/89?assignee=5f3543bb3e9e2e004db3189d&selectedIssue=CPDEL-584)
Tried this a few different ways but this seemed this most straight forward. 
2. Login as admin `admin@example.com`
3. Go to the ambition modules pages and click edit module
4. Add a page header and save changes

CPDEL-584 change ambition module title

---

app/views/dashboard/_dashboard_mentor.html.erb
spec/cypress/integration/TrainingAndSupport.feature

[581](https://dfedigital.atlassian.net/jira/software/projects/CPDEL/boards/89?assignee=5f3543bb3e9e2e004db3189d&selectedIssue=CPDEL-581)
Ticket:
2. Login as a mentor `ambition-institute-mentor@example.com`
3. Check what you see matches the changes in the ticket and prototype (The prototype has a typo that's mentioned in the ticket)
https://ecf-engage-and-learn-mentor.herokuapp.com/dev/tf/home

Update mentor dashboard

---

app/controllers/privacy_policies_controller.rb
app/views/layouts/_support_links.html.erb
app/views/layouts/application.html.erb
app/views/privacy_policies/show.html.erb
config/routes.rb
spec/cypress/integration/CipLessons.feature
spec/cypress/integration/Privacy.feature
spec/cypress/support/step_definitions/common-navigation.js

Ticket: https://dfedigital.atlassian.net/browse/CPDEL-512
2. Click on the 'Privacy' link in the footer.

Privacy policy

---

app/models/invite_email_ect.rb
app/models/invite_email_mentor.rb
app/models/tracked_email.rb
app/services/invite_participants.rb
spec/models/tracked_email_spec.rb

Ticket: https://dfedigital.atlassian.net/browse/CPDEL-593
1. You can't.

CPDEL-593: Add an option to force-send emails

---

app/controllers/users/sessions_controller.rb
app/models/user.rb
db/seeds/dummy_structures.rb
spec/models/tracked_email_spec.rb
spec/models/user_spec.rb
spec/requests/users/sessions_spec.rb

Ticket: https://dfedigital.atlassian.net/browse/CPDEL-626
Mostly adding tests. Cleaned up the logic in user class a little. 
2. Try logging in as `cip-less-ect@example.com` or `cip-less-mentor@example.com`

Handle cipless cip users

---

app/views/layouts/application.html.erb

Ticket: https://dfedigital.atlassian.net/browse/CPDEL-628

Fix google tag missing

---

app/webpacker/vendor_styles/govspeak/_tables.scss
app/webpacker/vendor_styles/govspeak/helpers/_markdown-typography.scss

Ticket: https://dfedigital.atlassian.net/browse/CPDEL-641

Increase font size in govepeak headers and tables

---

app/models/tracked_email.rb
app/views/layouts/application.html.erb
spec/models/tracked_email_spec.rb

We sent some emails, and I want to make double sure that we won't resend them (we would want to make a new email instead).

Do not resend the same email

---

app/controllers/core_induction_programmes/mentor_material_parts_controller.rb
app/models/analytics_data_layer.rb

Ticket: https://dfedigital.atlassian.net/browse/CPDEL-648

Add data layer to mentor material part pages

---

.github/workflows/deploy_to_dev.yml

Dev deployments don't seem to work, I want to investigate

Add manual dev deploys

---

Gemfile
Gemfile.lock
README.md

I added the line in the README as I noticed it was missing the other week but hadn't snuck it in yet. 
2. Login as admin, edit a lesson or mentor material with 
`$Details
$Heading
Heading
$EndHeading
$Content
Content
$EndContent
$EndDetails
`
and it should produce

Update ECF-govspeak Gemfile ref

---

app/controllers/core_induction_programmes/lesson_parts_controller.rb
app/controllers/core_induction_programmes/mentor_material_parts_controller.rb

We will want to delete some lesson parts, and we will want to preserve the order of other lesson parts.
2. Go to ambition lesson
3. Delete 'check' part
4. The 'reflect' part should be last

Improve deleting parts

---

Gemfile
Gemfile.lock

2. Go to a lesson with an accordion e.g. `/ambition/year-1/autumn-1/topic-1/part-1`
3. Edit the content in the accordion with some govspeak MD and it should render as expected.
4. Use the same url but on the dev environment to see how it compares - if you really want to.

Update ECF-govspeak Gemfile ref - updated accordion

---

Gemfile
Gemfile.lock
spec/cypress/integration/accessibility.js

Ticket: no ticket
Most of the changes are in the seed data, but that's not final - once i've got approval on everything else i'll get the latest data off staging and make the changes on that.

Fix accessibility tests and issues in material

---

app/controllers/core_induction_programmes/mentor_materials_controller.rb
app/models/core_induction_programme.rb
app/models/mentor_material.rb
app/policies/mentor_material_policy.rb
app/views/core_induction_programmes/mentor_material_parts/show_split.html.erb
app/views/core_induction_programmes/mentor_materials/_mentor_material_fields.html.erb
app/views/core_induction_programmes/mentor_materials/index.html.erb
db/migrate/20210706102517_remove_versions_from_cip_content.rb
db/migrate/20210706102557_ensure_mentor_materials_point_at_lessons.rb
db/schema.rb
spec/models/core_induction_programme.rb
spec/models/course_module_spec.rb
spec/models/course_year_spec.rb
spec/models/mentor_material_spec.rb
spec/policies/mentor_material_policy_spec.rb

No ticket, I just don't like them floating around. 
Includes a sneaky fix for splitting mentor material parts. 

Remove unused fields from db

---

Gemfile
Gemfile.lock
app/controllers/csp_reports_controller.rb
app/models/core_induction_programme_exporter.rb
config/initializers/rack_atack.rb
config/initializers/secure_headers.rb
config/routes.rb
spec/requests/csp_reports_spec.rb
spec/support/shared_examples/rate_limiting_support.rb

Ticket: https://dfedigital.atlassian.net/browse/CPDEL-564
I wanna steal what Matt is doing on https://github.com/DFE-Digital/early-careers-framework/pull/590/files

Add content security policy controller and secure headers

---

Gemfile
Gemfile.lock

Ticket:
[680](https://dfedigital.atlassian.net/jira/software/projects/CPDEL/boards/89?selectedIssue=CPDEL-680)
Updating ECF-govspeak to include session element id fix - See [ECF govspeak](https://github.com/DFE-Digital/ecf-govspeak/commit/b0202cdc4939b4ea29fbb5db3e11fa0a674663ec) for info

Update ECF govspeak Gemfile ref for session element id fix

---

app/controllers/application_controller.rb

Turns out healthcheck cannot be behind basic auth...

Do not hide healthcheck behind basic auth

---

app/components/lesson_summary_component.html.erb
app/views/privacy_policies/show.html.erb

Ticket: https://dfedigital.atlassian.net/browse/CPDEL-679
2. Sign in as mentor, check that a lesson with self-study materials has the correct copy
3. Privacy policy page had the wrong copy too.

Update 'self study' copy to 'self-study'

---

app/models/core_induction_programme_exporter.rb
app/models/course_lesson.rb
app/models/course_module.rb
db/migrate/20210712154859_add_order_to_mentor_materials.rb
db/schema.rb

Ticket: https://dfedigital.atlassian.net/browse/CPDEL-689
We need to add position to mentor materials. There are so few of them that I intend to order them by hand rather than in the app.

Add position to mentor materials

---

app/models/invite_email_ect.rb
app/models/invite_email_mentor.rb
app/services/invite_participants.rb
spec/models/tracked_email_spec.rb

I just got asked to send a few more emails. I want to be able to send them using our 'force-send' mechanism. 

I have a feeling we will need to send emails to unregistered users

---

app/views/layouts/application.html.erb
config/initializers/secure_headers.rb

No ticket, Kam told be about some bugs :)

Google analytics and service banner

---

app/models/invite_email_ect.rb
app/services/invite_participants.rb
app/services/register_and_partner_api/sync_users.rb
app/views/dashboard/show.html.erb
spec/services/register_and_partner_api/sync_users_spec.rb

We probably don't need to create emails we never intend to send.

Reduce users and emails

---

app/controllers/core_induction_programmes/mentor_materials_controller.rb
app/helpers/time_description_helper.rb
app/models/course_lesson.rb
app/models/mentor_material.rb
app/views/core_induction_programmes/mentor_material_parts/show.html.erb
app/views/core_induction_programmes/mentor_materials/_mentor_material_fields.html.erb
app/views/core_induction_programmes/mentor_materials/show.html.erb
db/migrate/20210722082231_add_completion_time_to_mentor_materials.rb
db/schema.rb
spec/helpers/time_description_helper_spec.rb
spec/models/course_lesson_spec.rb
spec/models/mentor_material_spec.rb

Ticket: https://dfedigital.atlassian.net/browse/CPDEL-710
I made a helper to share the display of minutes between mentor materials and lessons.
2. Sign in as admin
3. Go to a mentor material of your choice
4. Click on 'Edit' button
5. There should be a field for specifying duration time
6. And when filled the duration should show on the mentor material page

Mentor material duration

---

config/initializers/secure_headers.rb
spec/cypress/integration/accessibility.js

Saw a bunch of console errors
2. Get to a page with youtube embedding.
3. There should be much less console errors (only blocked things now are about youtube ads, which I am personally fine with).

Allow youtube embeddings to do their thing in our content security policy

---

.github/workflows/test.yml
Dockerfile
config/initializers/secure_headers.rb

We need some fixes which I found out about recently.

Small fixes

---

app/views/start/index.html.erb

Ticket: [738](https://dfedigital.atlassian.net/jira/software/projects/CPDEL/boards/89?assignee=5f3543bb3e9e2e004db3189d&selectedIssue=CPDEL-738)
2. You're there

CPDEL-738 edit start page text

---

app/controllers/accessibility_statements_controller.rb
app/views/accessibility_statements/show.html.erb
app/views/layouts/_support_links.html.erb
config/routes.rb
spec/cypress/integration/AccessibilityStatement.feature
spec/cypress/support/step_definitions/common-navigation.js
spec/requests/accessibility_statement_spec.rb

Ticket: [663](https://dfedigital.atlassian.net/jira/software/projects/CPDEL/boards/89?assignee=5f3543bb3e9e2e004db3189d&selectedIssue=CPDEL-663)
See linked ticket for more info [508](https://dfedigital.atlassian.net/browse/CPDEL-508)
2. Link to accessibility statement is in the footer

CPDEL-663 Add accessibility statement

---

documentation/release_process.md

No ticket, the release process doc just needed amending slightly

Update release process docs

---

.github/workflows/deploy_to_dev.yml
.github/workflows/deploy_to_production.yml
.github/workflows/deploy_to_staging.yml
.github/workflows/review.yml
terraform/app/modules/paas/main.tf
terraform/app/modules/paas/variables.tf
terraform/app/terraform.tf
terraform/app/variables.tf

Things are a bit broken on dfe paas
Stolen from R&P
Review app won't deploy, need to force merge this one I think :(

Fix terraform dockerhub oopsie

---

app/models/invite_email_ect.rb
app/models/invite_email_mentor.rb
app/models/tracked_email.rb
app/services/invite_participants.rb
app/services/register_and_partner_api/sync_users.rb
spec/fixtures/files/api/users.json
spec/models/tracked_email_spec.rb
spec/services/invite_participants_spec.rb
spec/services/register_and_partner_api/sync_users_spec.rb
terraform/workspace-variables/dev_app_env.yml
terraform/workspace-variables/production_app_env.yml
terraform/workspace-variables/review_app_env.yml
terraform/workspace-variables/staging_app_env.yml

Ticket: [720](https://dfedigital.atlassian.net/jira/software/projects/CPDEL/boards/89?selectedIssue=CPDEL-720)
We've removed the date restriction on the invite email to users with a featureflag. There's some changes in the terraform workspace variables. **Prod and review-apps** have the `EMAIL_SENDING_ENABLED: false`, where as **staging and deployed development** are set too true. 

Cpdel 720 update onboarding email check

---

terraform/workspace-variables/production_app_env.yml

Ticket: [709](https://dfedigital.atlassian.net/jira/software/projects/CPDEL/boards/89?selectedIssue=CPDEL-709)
Enabling email sending on prod. Email templates in notify have been updated.

Turn feature flag email sending on for production

---

app/helpers/dashboard_helper.rb
app/helpers/training_and_support_helper.rb
app/mailers/user_mailer.rb
app/models/invite_email_ect.rb
app/models/user.rb
app/services/utm_service.rb
app/views/core_induction_programmes/years/_nqt_plus_one_banner.html.erb
app/views/core_induction_programmes/years/show.html.erb
app/views/dashboard/show.html.erb
app/views/start/index.html.erb
app/views/training_and_support/_guidance_nqt_plus_one.html.erb
app/views/training_and_support/guidance_question.html.erb
app/views/training_and_support/show.html.erb
db/seeds/dummy_structures.rb
spec/factories/early_career_teacher_profiles.rb
spec/factories/users.rb
spec/models/tracked_email_spec.rb

Ticket: https://dfedigital.atlassian.net/browse/CPDEL-835
Adds a new invitation email for nqt plus one ects, and content tweaks for these users (mainly informing the user to ignore mentions of mentors etc)

CPDEL 835 NQT+1 participant journey

---

app/views/core_induction_programmes/years/show.html.erb

Ticket: [862](https://dfedigital.atlassian.net/jira/software/projects/CPDEL/boards/89?assignee=5f3543bb3e9e2e004db3189d&selectedIssue=CPDEL-862)
Nope, everything is straightforward. 
2. Login as a mentor - teach-first-mentor@example.com and ambition-institute-mentor@example.com and go to year 2. 
3. Login as an ECT - teach-first-early-career-teacher@example.com and ambition-institute-early-career-teacher@example.com and go to year 2.

Update year 2 holding content for TF and Ambition

---

app/controllers/cip_change_alert_controller.rb
app/helpers/dashboard_helper.rb
app/helpers/path_helper.rb
app/models/cip_change_message.rb
app/models/user.rb
app/services/register_and_partner_api/sync_users.rb
app/views/cip_change_alert/guidance.html.erb
app/views/cip_change_alert/start.html.erb
app/views/dashboard/show.html.erb
config/routes.rb
db/migrate/20210819101736_add_cip_change_message.rb
db/schema.rb
db/seeds/dummy_structures.rb
spec/cypress/app_commands/scenarios/ect_cip_change.rb
spec/cypress/integration/CipChangeAlert.feature
spec/cypress/support/step_definitions/common-navigation.js
spec/factories/cip_change_message.rb
spec/factories/users.rb
spec/fixtures/files/api/users.json
spec/rails_helper.rb
spec/services/register_and_partner_api/sync_users_spec.rb

Ticket: https://dfedigital.atlassian.net/browse/CPDEL-713

[CPDEL-713] CIP change alert

---

.github/workflows/export_course_lesson_data_report.yml

Also some renaming / removal of needless step installing conduit
Ticket:

Fix dev paas space name in export workflow

---

.github/workflows/export_course_lesson_data_report.yml

Attempt to fix bq csv loading

---

.github/workflows/export_course_lesson_data_report.yml

Fix course lesson data csv loading and point at production
