DFE-Digital/ecf-engage-and-learn

app/models/course_lesson_progress.rb, app/models/early_career_teacher_profile.rb, db/migrate/20210209172653_create_course_lesson_progresses.rb, db/migrate/20210210120844_add_uniqueness_constraint_to_course_lesson_progresses.rb, db/schema.rb, spec/factories/course_lesson_progresses.rb, spec/models/course_lesson_progress_spec.rb, spec/models/early_career_teacher_profile.rb
Teachers need to be able to track their progress for individual lessons, to be able to do this we need to link up early career teachers and course lessons. 
- Adding migrations that create CourseLessonProgress table and add a uniqueness constraint so as not to generate duplicate records of a teachers progress against the same lesson.
- Updated Schema
- Adding model tests for CourseLessonProgresses, along with a Factory
- Additional association tests for EarlyCareerTeacherProfile model
I've only included two course lesson progress states for the minute. These are likely to be added too later on. 
As mentioned above.
=> Tracking lesson progress

.githooks/pre-commit, app/controllers/core_induction_programme/lessons_controller.rb, app/controllers/core_induction_programme/modules_controller.rb, app/controllers/core_induction_programme/years_controller.rb, app/helpers/cip_breadcrumb_helper.rb, app/views/core_induction_programme/lessons/edit.html.erb, app/views/core_induction_programme/lessons/show.html.erb, app/views/core_induction_programme/modules/edit.html.erb, app/views/core_induction_programme/modules/show.html.erb, app/views/core_induction_programme/years/edit.html.erb, app/views/core_induction_programme/years/show.html.erb, app/views/dashboard/show.html.erb
I want CIP navigation to be easier
Add breadcrumbs using govuk-components to our cip pages. 'home' should go to dashboard when user is logged in, and to cip page otherwise.
Add list of modules to ect dashboard.
Commit by commit, maybe check out the review app. `early-career-teacher@example.com` should log you in to the dashboard. 
We will probably need to add some cypress tests for it later.
=> Add breadcrumbs

app/controllers/users/sessions_controller.rb, app/models/early_career_teacher_profile.rb, app/models/mentor_profile.rb, app/models/user.rb, app/views/dashboard/show.html.erb, db/migrate/20210215114306_create_mentor_profiles.rb, db/migrate/20210215121631_add_mentor_profile_to_early_career_teacher_profile.rb, db/schema.rb, db/seeds/dummy_structures.rb, spec/factories/mentor_profiles.rb, spec/factories/users.rb, spec/models/early_career_teacher_profile.rb, spec/models/mentor_profile_spec.rb
There will be mentors for ECF that will need to access the service. This adds the initial creation of these users.
- Migrations to add MentorProfile and linking ECTProfiles to a mentor
- Updated Schema
- MentorProfile model tests
- Updated ECTProfile model tests
- Creating a Mentor in dummy seed data, with a ECT being assigned a Mentor
- Mentor email added to test users to log in automatically.
As above
=> Add mentor profile

app/controllers/core_induction_programme/lesson_parts_controller.rb, app/forms/split_lesson_part_form.rb, app/policies/course_lesson_part_policy.rb, app/views/core_induction_programme/lesson_parts/show.html.erb, app/views/core_induction_programme/lesson_parts/show_split.html.erb, app/views/layouts/application.html.erb, app/webpacker/styles/application.scss, config/routes.rb, spec/forms/split_lesson_part_form.rb, spec/policies/course_lesson_part_policy_spec.rb, spec/requests/core_induction_programme/course_lesson_part_spec.rb
Lessons are long. We want to split them.
Here is the UI to split them.
1. Add a button and a page for splitting a lesson part.
2. Add endpoints for splitting a lesson part.
3. Add controller methods and policies for splitting a lesson part.
I haven't added lesson part navigation yet. That's next PR.
I opted to use more space than govuk pages use on the split page. That's because I think it is really convenient to see the old and new lesson part side-by-side. And for that, 960px that gov pages believe in, is too narrow. I intend to show it to Mark A (who will likely be the person who interacts with it the most) and see if he likes it.
1. Not testing the presence of the button.
2. Tested with request tests (rspec).
3. Tested with request tests and unit tests (rspec).
=> Split lesson parts

app/components/progress_label_component.rb, app/controllers/core_induction_programme/progress_controller.rb, app/models/course_lesson_progress.rb, app/views/core_induction_programme/lesson_parts/show.html.erb, spec/cypress/integration/cip-stories-early-career-teacher.js, spec/requests/core_induction_programme/progress_spec.rb
https://trello.com/c/iPgtIa2T/164-update-progress-setting-to-radios
- Add "discussion needed" status to lesson progress
- Turn previous checkbox into radios with multiple options for ECTs
My ruby might be in need of improvement!
=> Add discussion needed progress status

app/controllers/core_induction_programme/lessons_controller.rb, app/models/course_lesson.rb, app/views/core_induction_programme/lesson_parts/show.html.erb, app/views/core_induction_programme/lessons/edit.html.erb, app/views/core_induction_programme/lessons/show.html.erb, app/views/core_induction_programme/modules/show.html.erb, app/webpacker/styles/application.scss, app/webpacker/styles/course_lesson.scss, db/migrate/20210224162240_add_completion_time_in_minutes_to_course_lessons.rb, db/schema.rb, spec/cypress/integration/cip-stories-admin.js, spec/models/course_lesson_spec.rb, spec/requests/core_induction_programme/course_lesson_spec.rb
Course lessons need to be able to have the duration time set and edited. This will be done by DfE admin
`e21a83f` - Updates to the db with a migration and schema, add completion_time_in_minutes to course_lessons
`5b0e2b1` and `8053036` - Changes to the models and controllers.
`ce829ed` Updates to relevant views - Duration now shows in the course_module#show, course_lesson#show and #edit, and course_lesson_parts#show
Converting minutes is a bit clunky in the CL model. Also, I couldn't see a way to add + only integers in the migration so have just done validations in the model. 
**Stylings** have been added but i am not 100% on what the convention is for customising them. They've not been added to course module because i felt they were being displayed as shown on Dom's [figma](url) 
Updated …
=> Edit course lesson time

app/helpers/cip_breadcrumb_helper.rb, app/views/core_induction_programme/years/edit.html.erb, app/views/core_induction_programme/years/show.html.erb, spec/helpers/cip_breadcrumb_helper_spec.rb
The existing breadcrumbs don't include the page that the user is currently on or allow the user to return to the show page when editing using the breadcrumbs.
- updating breadcrumb helper to add breadcrumbs for course_year
- amending path of course_module and course_lesson breadcrumb 
- adding a method for the end crumb that shows either a link or string depending whether the user is on show or edit. As below 
Had a weird problem with 2 tests failing on course lesson parts. It's not been replicated in github or on Michals laptop. It sorted itself once the db was dropped and recreated. If this happens on others devices it could need further looking at. 
Testing of breadcrumb helper, including testing for behaviour with show and edit actions.
=> Add current page user is visiting to breadcrumbs

app/views/core_induction_programme/lesson_parts/show.html.erb, spec/cypress/integration/cip-stories-admin.js, spec/cypress/integration/cip-stories-early-career-teacher.js
Text on buttons was a bit unclear and surprising on playback.
Update button text to say 'lesson part' rather than 'lesson content'
N/A
Updated cypress tests
=> Update copy to make it more intuitive

app/controllers/core_induction_programme/lesson_parts_controller.rb, app/models/course_lesson_part.rb, app/policies/course_lesson_part_policy.rb, app/views/core_induction_programme/lesson_parts/edit.html.erb, app/views/core_induction_programme/lesson_parts/show.html.erb, app/views/core_induction_programme/lesson_parts/show_delete.html.erb, config/routes.rb, spec/models/course_lesson_part_spec.rb, spec/policies/course_lesson_part_policy_spec.rb, spec/requests/core_induction_programme/course_lesson_part_spec.rb
Admin can split out a lesson in to parts. We want them to also be able to delete If they can add, we want them to be able to delete parts
- Updated routes 
- Functionality for admin to delete a course lesson part, providing additional step to confirm. 
- Update testing for requests to delete and view show_delete page 
- Updating CourseLessonPart model and tests
- amending it block statements for non-admin user requests, it didn't reflect what was being tested - probably my bad from a previous commit. 
I added dependant destroy to the model during testing as it was raising a violation of foreign key constraint on update or delete. Without this, the delete would still work in the app, but not in testing. Probably be helpful to discuss why this was happening. 
There's no check to see if …
=> Lesson part deletion

app/controllers/cookies_controller.rb, app/forms/cookies_form.rb, app/views/cookies/_banner.html.erb, app/views/cookies/show.html.erb, app/views/layouts/application.html.erb, app/webpacker/packs/application.js, app/webpacker/packs/cookie-banner.js, config/routes.rb, spec/cypress/integration/cookies.js, spec/requests/cookies_spec.rb
Nicked the copy from https://www.notifications.service.gov.uk/cookies - I imagine it'll need changing at some point in the future!
- Add a cookie page explaining what cookies we use. We don't use GA yet but apparently we're going to.
- Add a cookie banner to every page but the cookie page when consent hasn't been given yet. When JS is available, doesn't require a page reload to use.
I'll be send the same code to the other repo so would appreciate some team one reviews here too.
I don't have access to IE to test this, but it could use some testing.
=> Add cookie page and banner

app/controllers/core_induction_programmes/years_controller.rb, app/models/course_year.rb, app/policies/course_year_policy.rb, app/policies/user_policy.rb, app/views/core_induction_programmes/index.html.erb, app/views/core_induction_programmes/show.html.erb, app/views/core_induction_programmes/years/edit.html.erb, app/views/core_induction_programmes/years/new.html.erb, config/routes.rb, db/migrate/20210318163012_change_core_induction_programme_id_null_on_course_years.rb, db/schema.rb, spec/cypress/integration/cip-stories-admin.js, spec/models/core_induction_programme.rb, spec/models/course_year_spec.rb, spec/policies/course_year_policy_spec.rb, spec/requests/core_induction_programme/course_year_spec.rb
We want admin to be able to create additional years, Year 1, Year 2 etc.
- create a migration that sets the core_induction_programme_id to null: false(We don't want to have course_years that aren't assigned to a cip). 
- updated routes and policies to allow admin to create a new course year, whilst restricting non-admin users. 
- updated views, including adding new.html.erb for creating a course year. 
- updated specs for the above
I had a look at various ways of doing the migration to add null: false. 2-3 different ways worked, change_column_null, add_column/remove_column and the up/down set in the migration. I went with this as my first attempt with change_change column didn't allow a rollback. Also adding then removing the same column just with null: false seemed unnecessary. The …
=> Create additional years for a cip

app/controllers/core_induction_programmes_controller.rb, app/controllers/start_controller.rb, app/controllers/users/sessions_controller.rb, app/policies/core_induction_programme_policy.rb, app/views/start/index.html.erb, config/routes.rb, db/seeds/dummy_structures.rb, spec/cypress/integration/aaa-meta.js, spec/cypress/integration/accessibility.js, spec/cypress/integration/cip-stories-early-career-teacher.js, spec/policies/core_induction_programme_policy_spec.rb, spec/requests/core_induction_programme/core_induction_programme_spec.rb, spec/requests/users/logout_spec.rb
We want to restrict access for ECTs so that they only have access to the cip they are enrolled on. 
- Implement CoreInductionProgrammePolicy, restricting index to admin and show to only the cip the ect is enrolled on
- Additional test user ECT profiles. Each CIP has an ECT profile assigned to it.
- Logout now redirects to sign_in page.
The logout redirects to sign_in because we've restricted the index to admin only. root_url is also the index page so we may need to think about what the landing page is. 
Additional tests have been included for the CoreInductionProgrammePolicy and requests.
=> Restrict cip access for ect

lib/tasks/safe_reset.rake, terraform/workspace-variables/dev.tfvars, terraform/workspace-variables/review.tfvars
So dev environment gets purged every now and then - to keep it from getting too messy, and to automatically bring staging changes into it. 
Add a rake task that only works in dev environments. The task deletes contents of our db and runs the seed files. 
Already done it on R&P.
=> Reset db on re-deploy on dev

app/controllers/application_controller.rb, app/controllers/username_controller.rb, app/models/user.rb, app/views/layouts/application.html.erb, app/views/username/new.html.erb, config/locales/devise.en.yml, config/routes.rb, db/migrate/20210412150041_add_account_created_to_user.rb, db/schema.rb, spec/factories/users.rb, spec/requests/username_request_spec.rb, spec/requests/users/sessions_spec.rb
We want to ask the users to create a username on their first login - or rather, on every login until they complete the flow. 
JIRA ticket: https://dfedigital.atlassian.net/browse/CPDEL-207
1. Add a flag to the user model checking whether they finished this lovely flow.
2. If yes, log them in as usual.
3. If not, log them in, and ask for username. 
I decided against using `confirmed` from devise - I think there is some magic surrounding it, and we will almost certainly end up discarding it.
Adding a flag to the db seemed like the easiest way of letting the users ignore username creation. If they want to they can press 'continue' and we will keep using their full name. And they will never see that flow again. 
I added request specs.
Would be useful to check the behaviour matches …
=> CPDEL-207: Confirm account

spec/cypress/integration/Login.feature, spec/cypress/integration/accessibility.js, spec/cypress/support/step_definitions/common-interaction.js, spec/cypress/support/step_definitions/common-navigation.js
- Login is now cucumber specs
- CIP was already being tested (in the CIP admin stories)
- The remaining accessibility tests are too complicated to be turned into cucumber specs
=> Cucumberise login tests and remove duplicate a11y tests 🥒

app/controllers/core_induction_programmes/mentor_materials_controller.rb, app/models/core_induction_programme.rb, app/policies/mentor_material_policy.rb, app/views/core_induction_programmes/mentor_materials/_mentor_material_fields.html.erb, app/views/core_induction_programmes/mentor_materials/edit.html.erb, app/views/core_induction_programmes/mentor_materials/show.html.erb, config/routes.rb, spec/cypress/integration/CipStoriesAdmin.feature, spec/cypress/support/step_definitions/common-navigation.js, spec/policies/mentor_material_policy_spec.rb, spec/requests/core_induction_programme/mentor_material_spec.rb
We want to be able to edit mentor materials.
Add editing mentor materials for admin users. Add needed policies.
This is for internal use only - so we can fix any issues we run into. Closely follows editing all other content-related things.
Unit testing. I think it makes sense to hold off cucumber tests until we have concrete user stories for them.
If you want to see it in action, login as admin, go to `/mentor-materials` in the url, click on a mentor material and you should see a green 'edit' button.
=> Editing mentor materials

app/views/core_induction_programmes/lesson_parts/show.html.erb
- Incorrect markup used on govuk bulleted list
- Use correct markup for govuk bulleted list displaying contents list at top of a lesson parts page
- Markup should adhere to govuk design system documented at https://design-system.service.gov.uk/styles/typography/#lists
- Login as admin
- View a lesson part that has a contents section at the top
- Bulleted list should now align with the LHS
=> Fix contents list shown at top of lesson parts

app/helpers/cip_breadcrumb_helper.rb, app/models/course_module.rb, app/views/core_induction_programmes/modules/show.html.erb, spec/cypress/integration/CipStoriesAdmin.feature, spec/cypress/support/commands.js, spec/helpers/cip_breadcrumb_helper_spec.rb, spec/models/course_module_spec.rb, spec/requests/core_induction_programme/course_module_spec.rb
This is a hack to make the titles match the wireframes, which say "First half-term: blabla" under an "Autumn" title in the year page and "Autumn first half-term: blabla" in the module page.
This is hopefully temporary - a quick fix to get in before user testing.
I've repurposed an existing method which was being used in the admin interface only:
yes
=> Show term in module title (hacky)

.githooks/pre-commit, .github/workflows/lint.yml, .github/workflows/test.yml, app/controllers/core_induction_programmes/mentor_materials_controller.rb, app/policies/mentor_material_policy.rb, app/views/core_induction_programmes/mentor_materials/_mentor_material_fields.html.erb, app/views/core_induction_programmes/mentor_materials/index.html.erb, app/views/core_induction_programmes/mentor_materials/new.html.erb, config/routes.rb, spec/cypress/integration/CipStoriesAdmin.feature, spec/cypress/support/step_definitions/common-navigation.js, spec/policies/mentor_material_policy_spec.rb, spec/requests/core_induction_programme/mentor_material_spec.rb
After spending a while looking at mentor materials, I think we won't be able to migrate all of them automatically - some content is hard hard to split without also making it unhelpful, and for that content we will probably just want to input it by hand.
Add the new and create endpoints, actions, policy, tests.
Add a sneaky improvement to github action name, so pre-commit hook can be nicer. I hope it works. 
Log in as admin. Go to `/mentor-materials` in the url. There should be a button for creating a new mentor material.
I added request specs and cucumber tests.
=> Create mentor materials as admin

app/views/core_induction_programmes/lesson_parts/edit.html.erb, app/views/core_induction_programmes/lesson_parts/show.html.erb, app/views/core_induction_programmes/lesson_parts/show_split.html.erb, app/views/core_induction_programmes/years/_module_list.html.erb, app/views/core_induction_programmes/years/edit.html.erb, app/views/dashboard/show.html.erb, app/views/layouts/_page_navigation.html.erb, app/views/layouts/_support_links.html.erb, app/views/layouts/application.html.erb, app/webpacker/styles/app_task_list.scss, spec/cypress/integration/Navigation.feature
https://dfedigital.atlassian.net/browse/CPDEL-411
https://dfedigital.atlassian.net/browse/CPDEL-412
also:
- wrap groups of buttons in govuk-button-group element for consistency
- "One self-study sessions" -> "One self-study session"
- Remove line from bottom of task list when no self-study sessions
=> Minor visual improvements

app/models/course_lesson_progress.rb, app/views/core_induction_programmes/lesson_parts/show.html.erb
https://dfedigital.atlassian.net/browse/CPDEL-422
There was a bug in progress input error - the error from summary was not taking the user to the actual error message when clicked. 
Also, change copy for https://dfedigital.atlassian.net/browse/CPDEL-433
Use @asmega 's advice to pass a parameter to one of the radio buttons telling it to link the errors to it.
Log in as `ucl-early-career-teacher@example.com`, go to any lesson, go to last page part, select nothing and click the submit button. You should see an error. Click on the error in the summary at the top of the page. You should be taken to the radios at the bottom of the page.
I am not sure how to test it. I guess in cucumber we could recreate this situation, and click on the error message in the summary, but is there a way in cypress …
=> CPDEL-422: Fix errors to radios not linking to bottom of the page

.env.test, app/models/register_and_partner_api/user.rb, app/services/register_and_partner_api/sync_users.rb, documentation/debugging_in_govpaas.md, lib/devise/strategies/yolo_authenticatable.rb, spec/cypress/cypress_helper.rb, spec/fixtures/files/api/users.json, spec/lib/devise/strategies/yolo_authenticatable_spec.rb, spec/requests/core_induction_programme/course_lesson_spec.rb, spec/requests/users/sessions_spec.rb, spec/services/register_and_partner_api/sync_users_spec.rb, spec/spec_helper.rb
- User data needs to come from Register & Partner so users can login to view their course
- Updated service so it can now sync existing users from existing Register & Partner api
- Extremely naive implementation where we sync users when a user attempts to login and they do not exist in our database
- Not sure if this will work if deployed. ENV vars will probably need to be setup and point to dev Register & Partner
- There will be syncing issues if users change email addresses to existing ones due to validation. Should probably raise a ticket to resolve in the future
- update `.env.development` and set `REGISTER_AND_PARTNER_URL` to the dev instance of Register & Partner
- Attempt to sign in as a user that exists on that api endpoint and not your local system
- Should create the user and …
=> [CPDE-383] Sync users on sign in attempt

app/services/register_and_partner_api/sync_users.rb, db/migrate/20210520144310_add_register_and_partner_id_to_users.rb, db/schema.rb, spec/fixtures/files/api/users.json, spec/services/register_and_partner_api/sync_users_spec.rb
Users in register and partner can change their email address. However this is what we're currently using to check if they exist on our service. R&P send us the users id so we can store this on our side, avoiding us creating duplicate users. [Jira ticket](https://dfedigital.atlassian.net/browse/CPDEL-454)
Migration to add `register_and_partner_id` to Users table
Changes sync_users method to find user by their register_and_partner_id
Having the same user in the users.json file but with a changed email feels like cheating but i couldn't find a simpler way of testing the email updated. 
Additional test for making sure the user isn't created twice and their email is updated. As above with the cheating. 
You could try it manually by following [these …
=> [CPDEL-454] Add reg and partner field to user

app/services/register_and_partner_api/sync_users.rb, spec/fixtures/files/api/users.json, spec/services/register_and_partner_api/sync_users_spec.rb
We can now receive the type of user and their cip from the R&P api. We want to use this to create the right profile and assign their cip to them on E&L.
Updated user sync method that creates a users profile based on the user_type sent and assigns them a cip based on the cip_type. 
We're currently only doing this for ECTs as we only receive a type of `early_career_teacher` and `other`. The other type will create a mentor profile. 
See [R&P PR](https://github.com/DFE-Digital/early-careers-framework/pull/400) for further info on the changes made on their side to see how what data is being sent and how it's selected. An enum is used for sending CIP_TYPE and USER_TYPE
A couple changes to the sync_users_spec and an additional test to check user type.
=> Update user sync

app/views/core_induction_programmes/lesson_parts/show.html.erb, app/views/core_induction_programmes/modules/show.html.erb, app/webpacker/styles/app_task_list.scss
[Jira ticket 423](https://dfedigital.atlassian.net/browse/CPDEL-423)
[Jira ticket 481](https://dfedigital.atlassian.net/browse/CPDEL-481)
Everyone except an ECT will see a link captioned View the teacher's self-study materials. ECT's see the same as before 'Work through the self-study materials
Kam and Mark A discussed about Ambition, TF and UCL all having the same caption. Mark was happy to use the same for all 3. EDT is also using the same for now until there's been a firm decision made on how to show ECT materials.  
None
=> Update lesson and module show views

.github/PULL_REQUEST_TEMPLATE.md, app/views/cookies/_banner.html.erb, app/views/core_induction_programmes/lesson_parts/edit.html.erb, app/views/core_induction_programmes/lesson_parts/show.html.erb, app/views/core_induction_programmes/lesson_parts/show_delete.html.erb, app/views/core_induction_programmes/lesson_parts/show_split.html.erb, app/views/core_induction_programmes/lessons/edit.html.erb, app/views/core_induction_programmes/lessons/new.html.erb, app/views/core_induction_programmes/mentor_materials/edit.html.erb, app/views/core_induction_programmes/mentor_materials/new.html.erb, app/views/core_induction_programmes/modules/edit.html.erb, app/views/core_induction_programmes/modules/new.html.erb, app/views/core_induction_programmes/years/edit.html.erb, app/views/core_induction_programmes/years/new.html.erb, app/views/govspeak_test/show.html.erb, app/views/preferred_name/edit.html.erb
I think the PR template could use a makeover.
Also, Chris is keen on adding ids to forms, and shockingly Rails doesn't do that by itself, unless you use `form_for`, which seems to be a somewhat old tag, that is likely to be removed at some point in future (https://stackoverflow.com/questions/43868976/rails-5-form-for-vs-form-with)
=> Update PR template and add ids to forms

app/views/cookies/show.html.erb, app/views/layouts/application.html.erb, config/environments/deployed_development.rb, config/environments/production.rb, config/environments/staging.rb, spec/cypress/integration/Cookies.feature, spec/cypress/integration/StartPage.feature
[Jira ticket](https://dfedigital.atlassian.net/jira/software/projects/CPDEL/boards/89?assignee=5f3543bb3e9e2e004db3189d&selectedIssue=CPDEL-506)
Adding a link to cookies page in the footer
Renaming the boilerplate session store
The acceptance criteria in the Jira ticket was 
- the service footer contains a link ‘Cookies’ (see screenshot below) which links to the cookie page 
- the cookie page is up-to-date and correct
The second point was checked with Michal and confirmed it's up to date. 
Percy test to check cookies is in the footer
=> CPDEL 506 add cookie link in footer

app/webpacker/styles/dashboard.scss
Ticket: [515](https://dfedigital.atlassian.net/jira/software/projects/CPDEL/boards/89?assignee=5f3543bb3e9e2e004db3189d&selectedIssue=CPDEL-515)
Nope, everything is straightforward. The existing govuk-button setting in dashboard.scss just needed some additional attributes.
2. Login as a mentor, e.g `ucl-mentor@example.com`
3. You should see the change straight away as it directs you to the dashboard after login
=> Change start-button color to blue

app/views/core_induction_programmes/years/show.html.erb, spec/cypress/integration/CipYears.feature, spec/requests/core_induction_programme/course_year_spec.rb
Ticket: https://dfedigital.atlassian.net/browse/CPDEL-495
2. Login as `ambition-institute-mentor@example.com`
3. Navigate to year 2 of CIP content, check it looks like what the ticket says
4. Logout, login as `ambition-institute-early-career-teacher@example.com`
5. Navigate to year 2 of CIP content, check it looks like what the ticket says
=> Display hard-coded text if year has no modules

app/controllers/users/sessions_controller.rb, app/models/invite_email_ect.rb, app/services/invite_participants.rb, app/services/register_and_partner_api/sync_users.rb, lib/tasks/invites.rake, spec/fixtures/files/api/users.json, spec/models/tracked_email_spec.rb, spec/services/invite_participants_spec.rb, spec/services/register_and_partner_api/sync_users_spec.rb
Ticket: https://dfedigital.atlassian.net/browse/CPDEL-490
Commit by commit should be pretty straightforward.
I put the logic for whether we want to create an email or not in the sync service. I guess it could live in an after create hook on a user, but at that time we might not yet know whether the user is a mentor or an ect.
I put the logic for whether to send an email or not in the email model.
When we get ECTs, we will create invite emails for them, but we won't send them. At some point we will probably need a job for sending unsent emails.
I added email sending for mentors too, because we want it, and it was easier to add it here than to split it into its own PR. 
1. You can't really. If you want to check that mentors receive an email, we would need to add a mentor that is whitelisted …
=> Send invites on user sync

app/models/mentor_material.rb, app/policies/core_induction_programme_policy.rb, app/policies/mentor_material_policy.rb, spec/policies/mentor_material_policy_spec.rb, spec/requests/core_induction_programme/mentor_material_spec.rb
Ticket: https://dfedigital.atlassian.net/browse/CPDEL-516
2. Login as admin.
3. Get a link of ambition mentor material.
4. Login as `ambition-institute-mentor@example.com` - you should be able to see the material when you go to that link.
5. Login as `ucl-mentor@example.com` - you should not be able to see that material.
6. Login as `ambition-institute-early-career-teacher@example.com` - you should not be able to see that material.
=> Restrict mentor materials to just mentors with right cip and admins

app/models/invite_email_mentor.rb, spec/models/tracked_email_spec.rb, spec/services/invite_participants_spec.rb
Ticket: [552](https://dfedigital.atlassian.net/browse/CPDEL-552)
Nope, everything is straightforward. It works the same as InviteEmailEct.
We've set the `INVITES_SENT_FROM` date as 30 June, the month has been agreed but not the day so I've put it as far away as possible for now. 
You can't.
=> [CPDEL-517] - onboarding emails can be sent automatically to mentors

app/views/core_induction_programmes/modules/show.html.erb, app/views/core_induction_programmes/years/_module_list.html.erb
Ticket: [538](https://dfedigital.atlassian.net/browse/CPDEL-538)
It's in the years overview and weekly lessons overview but it should look roughly like the below
ECT view weekly
ECT view yearly
Mentor view weekly
Mentor view yearly
2. Login in as an ECT `ambition-institute-early-career-teacher@example.com`
3. Check it looks like the ECT image above on yearly and weekly pages
4. Logout
5. Login as a Mentor `ambition-institute-mentor@example.com`
6. It should look like the Mentor image above on yearly and weekly pages
=> Add top section break in ECTs progress

app/jobs/sync_all_users_job.rb, app/services/register_and_partner_api/sync_users.rb, lib/tasks/cron.rake
Currently we rely on R&P being nice, and to know what we mean by 'the user was updated' - cause we sent them `updated_since` parameter. 
If it so happens that there is some tiny change here or there (say in that user's schools's cohort's induction programme changes), that doesn't trigger a change of that user's `updated_at` field on R&P, but is important for E&L, we want to have some way of updating it.
And this is this way - nightly job to sync all users.
=> Add a nightly job to sync all users

app/controllers/users/sessions_controller.rb, app/models/early_career_teacher_profile.rb, app/models/invite_email_ect.rb, app/models/invite_email_mentor.rb, app/models/mentor_profile.rb, app/models/user.rb, app/services/register_and_partner_api/sync_users.rb, db/migrate/20210614075746_add_induction_programme_choice_to_early_career_teacher_profile.rb, db/migrate/20210614075806_add_induction_programme_choice_to_mentor_profile.rb, db/schema.rb, db/seeds/dummy_structures.rb, spec/factories/early_career_teacher_profiles.rb, spec/factories/mentor_profiles.rb, spec/fixtures/files/api/users.json, spec/models/tracked_email_spec.rb, spec/requests/users/sessions_spec.rb, spec/services/register_and_partner_api/sync_users_spec.rb
Ticket: [549](https://dfedigital.atlassian.net/jira/software/projects/CPDEL/boards/89?assignee=5f3543bb3e9e2e004db3189d&selectedIssue=CPDEL-549)
The addition of induction_programme_choice to has been made in [PR-518](https://github.com/DFE-Digital/early-careers-framework/pull/518) on Register and Partner. 
We only store the induction programme choice for synced users. Do we want to set it default to core for all users?
2. Try to login as a cip user, `rp-mentor-ambition@example.com`, you should be able to login.
3. Try to login as a fip user, `rp-ect-ucl@example.com` or `rp-mentor-ucl@example.com and you should see an error page. 
You should see
=> Cpdel 549 stop fip user email and login

app/components/lesson_summary_component.html.erb, app/views/core_induction_programmes/lesson_parts/show.html.erb
Ticket: [565](https://dfedigital.atlassian.net/jira/software/projects/CPDEL/boards/89?assignee=5f3543bb3e9e2e004db3189d&selectedIssue=CPDEL-565)
2. Login as a mentor, e.g. `ambition-institute-mentor@example.com
3. Go to a module page.
4. Click "View the ECT's self-study materials"
5. You should see the images below 
Module page
Lesson page
=> CPDEL-565 change "teacher's" to "ECT's" for mentor view

app/services/register_and_partner_api/sync_users.rb, spec/fixtures/files/api/users.json, spec/services/register_and_partner_api/sync_users_spec.rb
We were not correctly importing core induction programmes :(
2. Try to log in as `rp-mentor-ambition@example.com`. You should be able to access your materials. Before this change there was no button to start.
=> CPDEL-563: Fix importing core induction programes

lib/tasks/cip_seed_dump.rake
vim wasn't a fan of doing this in the editor so i wrote a script for it - figured i'd add it to the rake task
why haven't i had to double escape the square brackets? i was expecting ruby to get rid of the escape characters
this is entire developer experience stuff and doesn't affect the actual product :)
=> Automatically handle generating cip_seed.rb as well as cip_seed_dump.rb

app/models/mentor_material.rb, app/webpacker/styles/govspeak/_section.scss
Multiple sections one after another had no spacing between them.
2. Type `govspeak_test` in the url
```
$Section
Test 1
$Section
$Section
Test 2
$Section
```
Should produce two grey sections separated by a small margin.
=> Add spacing between sections in govspeak

README.md, app/views/core_induction_programmes/lesson_parts/show.html.erb, app/views/core_induction_programmes/lessons/show.html.erb, app/views/core_induction_programmes/mentor_material_parts/show.html.erb, app/views/core_induction_programmes/mentor_materials/show.html.erb
No ticket. Reasonably often we need to go from uuid to path, or from path to uuid, and I thought we should make it easier for ourselves. 
2. Sign in as admin. Mentor materials and course lessons should show you their uuids on their pages.
3. Sign in as non-admin. You should not see the uuids.
=> Quality of life improvements for developer tickets

app/controllers/users/sessions_controller.rb, app/models/invite_email_ect.rb, app/models/invite_email_mentor.rb, app/models/user.rb, app/services/invite_participants.rb, app/services/register_and_partner_api/sync_users.rb, db/migrate/20210709100154_add_registration_completed_to_early_career_teacher_profiles.rb, db/migrate/20210709100207_add_registration_completed_to_mentor_profiles.rb, db/schema.rb, db/seeds/dummy_structures.rb, spec/factories/early_career_teacher_profiles.rb, spec/factories/mentor_profiles.rb, spec/fixtures/files/api/users.json, spec/models/tracked_email_spec.rb, spec/models/user_spec.rb, spec/requests/users/sessions_spec.rb, spec/services/register_and_partner_api/sync_users_spec.rb
Ticket: [653](https://dfedigital.atlassian.net/jira/software/projects/CPDEL/boards/89?assignee=5f3543bb3e9e2e004db3189d&selectedIssue=CPDEL-653)
- We need to check that has registered on R&P side before allowing them to access the materials on E&L. R&P haven't started this process fully yet but we can our initial structure for it. 
An automatic assignment of false has been added on R&P as a placeholder - see [R&P 682](https://github.com/DFE-Digital/early-careers-framework/pull/682#partial-pull-merging)
=> CPDEL-653 check user registration is complete

app/models/analytics_data_layer.rb, spec/models/analytics_data_layer_spec.rb
Ticket: [697](https://dfedigital.atlassian.net/jira/software/projects/CPDEL/boards/89?selectedIssue=CPDEL-697)
2. Inspect a course year page. 
3. type dataLayer in to the console
4. You should see the course year 1 or 2 in the output for cipYear
=> CPDEL-697-set-cipYear-datalayer-to-year-position

app/models/register_and_partner_api/user.rb, spec/spec_helper.rb
We renamed an endpoint on R&P to better suit what it is doing - `users` is too generic for our case (we only get mentors and ects in it).
So we need to change the path we query.
The R&P change is nice - they added a copy of the endpoint, to give us time to switch. 
R&P PR: https://github.com/DFE-Digital/early-careers-framework/pull/744
=> Update the users client path to point at new endpoint in R&P

Gemfile, Gemfile.lock, spec/cypress/integration/accessibility.js
Context
The ECF-govspeak version has been updated to fix an accessibility issue for duplicate IDs in information and call-to-action.
The frame size for youtube videos has also been increased. 
Go to the [ECF PR 15](https://github.com/DFE-Digital/ecf-govspeak/pull/15) and [ECF PR 16](https://github.com/DFE-Digital/ecf-govspeak/pull/16) to see these in detail. 
Accessibility tests are still failing but this is due to header order errors. I've added them to the list to skip. They'll need to be updated in staging. 
2. Go to a lesson with a video. 
3. Go to `/edt/year-1/summer-1/topic-5/part-3` and check that header ids increment.
=> Updated ecf govspeak ref

app/webpacker/styles/govspeak.scss, app/webpacker/styles/govspeak/_details.scss, app/webpacker/styles/govspeak/_highlights.scss
Ticket: [755](https://dfedigital.atlassian.net/jira/software/projects/CPDEL/boards/89?assignee=5f3543bb3e9e2e004db3189d&selectedIssue=CPDEL-755)
2. Go to `/teach-first/year-1/autumn-1/topic-4/part-2` for videos in an information block that have been resized. 
3. Go to `/ambition/year-1/autumn-1/topic-2/part-1` or find a video not in an information block to check it's not had an effect on other videos. 
**Information block youtube video**
**Details spacing**
=> Fix video bleeding in information blocks

app/helpers/cip_breadcrumb_helper.rb, spec/helpers/cip_breadcrumb_helper_spec.rb
Ticket: [764](https://dfedigital.atlassian.net/jira/software/projects/CPDEL/boards/89?selectedIssue=CPDEL-764)
There was a linked end crumbs so it needed a bit of tweaking to keep this. 
2. Go to years, modules or lessons and there should be no end unlinked crumb
3. Login as an admin and go to edit content. 
4. The page you've just come from should be linked in the end crumb. 
**Page with no end unlinked crumb**
**Edit page with end linked crumb**
=> CPDEL-764 remove final unlinked breadcrumb

config/environments/development.rb, documentation/register_and_partner_api_setup.md
Previously there was no active job queue adapter specified so it would use the async adapter:
https://api.rubyonrails.org/classes/ActiveJob/QueueAdapters/AsyncAdapter.html
This meant that the `rake cron:schedule` task would just run the tasks once and not reschedule them
as the async adapter is in-memory.
Set the queue adapter to be delayed_job as it is in other environments and add documentation on
how to run it locally.
Ticket:
n/a
=> Add docs and config for running jobs locally

app/models/analytics_data_layer.rb, app/models/user.rb, app/services/register_and_partner_api/sync_users.rb, db/seeds.rb, db/seeds/cohort_seed.rb, db/seeds/dummy_structures.rb, spec/factories/early_career_teacher_profiles.rb, spec/factories/mentor_profiles.rb, spec/fixtures/files/api/users.json, spec/models/analytics_data_layer_spec.rb, spec/services/register_and_partner_api/sync_users_spec.rb
Ticket: [776](https://dfedigital.atlassian.net/jira/software/projects/CPDEL/boards/89/backlog?selectedIssue=CPDEL-776)
We want to know whether a user is part of the 2020 cohort (NQT + 1) for our analytics data so we need to get this from R&P. We'll also want to distinguish between future cohorts and cut off access to the platform later down the line.
I'll open a separate PR on R&P to send that information. 
=> Add cohort to user sync

app/helpers/year_helper.rb, app/views/core_induction_programmes/years/show.html.erb, spec/cypress/integration/CipYears.feature
There can be a maximum of 2 CIP years. There will be an error trying to load any CIP year if
there are 3 in total, because a route can't be generated for the third year.
Ticket: https://dfedigital.atlassian.net/browse/CPDEL-649
=> [CPDEL-649] Hide "Create year" button when there are already 2

terraform/app/variables.tf
There were some fixes to dockerhub/terraform made a couple days ago on R&P and [E&L](https://github.com/DFE-Digital/ecf-engage-and-learn/pull/235), although R&Ps destroy workflow didn't work correctly. This is just a [copy of their change](https://github.com/DFE-Digital/early-careers-framework/pull/884) to prevent this happening to us as well. 
Set default values to the docker variables in terraform.
=> Set default docker vars to null

app/services/register_and_partner_api/sync_users.rb, spec/services/register_and_partner_api/sync_users_spec.rb
This api has recently changed to have a stricter parsing of the updated_since parameter and is now failing with bad
request because the timestamp we were sending was not in iso8601 format
Ticket:
=> Use iso8601 format when calling ecf-users api

app/services/register_and_partner_api/sync_users.rb, spec/fixtures/files/api/users.json, spec/services/register_and_partner_api/sync_users_spec.rb
Bug from original ticket: https://dfedigital.atlassian.net/browse/CPDEL-835
Found during end to end testing, we don't add nqt+1 participants in the typical way, so they won't be validated. So relax this check if the user is an nqt+1 ect.
=> CPDEL-835 Fix nqt+1 invites

app/models/invite_email_ect.rb, spec/factories/users.rb, spec/models/tracked_email_spec.rb
We recently relaxed the constraint for registration to be completed for nqt+1 participants in the user sync, though there is an extra check in the  email itself that also needs to be relaxed
Ticket:
=> Fix nqt+1 invites again

app/mailers/user_mailer.rb, app/models/reminder_email_mentor.rb, app/services/remind_participants.rb, app/services/utm_service.rb, spec/models/tracked_email_spec.rb, spec/services/remind_participants_spec.rb
Ticket: [801](https://dfedigital.atlassian.net/jira/software/projects/CPDEL/boards/89?selectedIssue=CPDEL-801)
We want to send a reminder email to all private beta mentors. It's going to be ran manually in the terminal with a list of emails we have already. 
2. Run it manually in the console.
=> Adds reminder email for mentors to sign in
